// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.WuZiQi
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIGameOver
    {
        
        public const string NAME = "UIGameOver";
        
        [SerializeField()]
        public UnityEngine.UI.Image ResultImage;
        
        private UIGameOverData mPrivateData = null;
        
        public UIGameOverData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIGameOverData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            ResultImage = null;
            mData = null;
        }
    }
}
